/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Force generate all headspace color variations
    'bg-headspace-cream',
    'bg-headspace-orange',
    'bg-headspace-orange-dark',
    'bg-headspace-slate',
    'bg-headspace-blue',
    'text-headspace-cream',
    'text-headspace-orange',
    'text-headspace-orange-dark',
    'text-headspace-slate',
    'text-headspace-blue',
    'border-headspace-cream',
    'border-headspace-orange',
    'border-headspace-orange-dark',
    'border-headspace-slate',
    'border-headspace-blue',
    'from-headspace-cream',
    'from-headspace-orange',
    'from-headspace-orange-dark',
    'from-headspace-slate',
    'from-headspace-blue',
    'to-headspace-cream',
    'to-headspace-orange',
    'to-headspace-orange-dark',
    'to-headspace-slate',
    'to-headspace-blue',
    'via-headspace-cream',
    'via-headspace-orange',
    'via-headspace-orange-dark',
    'via-headspace-slate',
    'via-headspace-blue',
    'hover:from-headspace-orange-dark',
    'hover:to-headspace-orange',
    'hover:to-headspace-orange-dark',
    'hover:via-headspace-orange',
    'border-headspace-orange/20',
    'border-headspace-orange/30',
  ],
  theme: {
    extend: {
      colors: {
        headspace: {
          orange: '#f58b44',
          'orange-dark': '#f06e1d',
          cream: '#fdf5eb',
          slate: '#4b5161',
          blue: '#52b6de',
        },
      },
    },
  },
  plugins: [],
}
