// PDF Export Utilities for HomeLLM
import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Export email as professional PDF
 */
export function exportEmailAsPDF(emailData, formData) {
  const doc = new jsPDF();

  // Add logo/branding
  doc.setFontSize(20);
  doc.setTextColor(245, 139, 68); // Headspace orange
  doc.text('HomeLLM', 20, 20);

  doc.setFontSize(10);
  doc.setTextColor(75, 81, 97); // Headspace slate
  doc.text('AI-Powered Home Health Advocacy Platform', 20, 28);

  // Add horizontal line
  doc.setDrawColor(245, 139, 68);
  doc.setLineWidth(0.5);
  doc.line(20, 32, 190, 32);

  // Document title
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Advocacy Email', 20, 45);

  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })}`, 20, 52);

  let yPos = 65;

  // Subject line
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Subject:', 20, yPos);
  doc.setFont(undefined, 'bold');
  const subjectLines = doc.splitTextToSize(emailData.subject, 150);
  doc.text(subjectLines, 45, yPos);
  doc.setFont(undefined, 'normal');

  yPos += (subjectLines.length * 7) + 10;

  // Sender information
  doc.setFontSize(10);
  doc.setTextColor(75, 81, 97);

  if (formData.senderName) {
    doc.text(`From: ${formData.senderName}`, 20, yPos);
    yPos += 5;
  }
  if (formData.senderEmail) {
    doc.text(`Email: ${formData.senderEmail}`, 20, yPos);
    yPos += 5;
  }
  if (formData.senderPhone) {
    doc.text(`Phone: ${formData.senderPhone}`, 20, yPos);
    yPos += 5;
  }
  if (formData.senderAddress) {
    doc.text(`Address: ${formData.senderAddress}`, 20, yPos);
    yPos += 5;
  }

  yPos += 5;

  // Recipient and issue info
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`To: ${formData.recipient}`, 20, yPos);
  yPos += 5;
  doc.text(`Issue Type: ${formData.issueType}`, 20, yPos);
  yPos += 5;
  doc.text(`Location: ${formData.location}, ${formData.city}, ${formData.state}`, 20, yPos);
  yPos += 5;
  doc.text(`Escalation Level: ${formData.escalationLevel}`, 20, yPos);
  yPos += 5;
  doc.text(`Urgency: ${formData.urgencyLevel}`, 20, yPos);

  yPos += 10;

  // Email body
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  const bodyLines = doc.splitTextToSize(emailData.body, 170);

  bodyLines.forEach(line => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, 20, yPos);
    yPos += 7;
  });

  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text('Generated by HomeLLM - For informational purposes only', 105, 285, { align: 'center' });
  }

  // Save the PDF
  const filename = `HomeLLM_Email_${formData.issueType}_${Date.now()}.pdf`;
  doc.save(filename);
}

/**
 * Export comprehensive evidence packet as PDF
 */
export function exportEvidencePacket(data) {
  const doc = new jsPDF();

  // Cover page
  doc.setFontSize(24);
  doc.setTextColor(245, 139, 68);
  doc.text('EVIDENCE PACKET', 105, 100, { align: 'center' });

  doc.setFontSize(16);
  doc.setTextColor(75, 81, 97);
  doc.text(data.formData.issueType.toUpperCase(), 105, 115, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`${data.formData.location}`, 105, 130, { align: 'center' });
  doc.text(`${data.formData.city}, ${data.formData.state}`, 105, 140, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Prepared: ${new Date().toLocaleDateString()}`, 105, 160, { align: 'center' });
  doc.text(`Prepared by: ${data.formData.senderName}`, 105, 170, { align: 'center' });

  doc.addPage();

  let yPos = 20;

  // Table of Contents
  doc.setFontSize(16);
  doc.setTextColor(245, 139, 68);
  doc.text('TABLE OF CONTENTS', 20, yPos);
  yPos += 15;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  const sections = [
    '1. Executive Summary',
    '2. Issue Details',
    '3. Timeline of Events',
    '4. Damage Assessment',
    '5. Evidence Documentation',
    '6. Regulatory Citations',
    '7. Advocacy Email',
    '8. Appendices'
  ];

  sections.forEach(section => {
    doc.text(section, 30, yPos);
    yPos += 8;
  });

  doc.addPage();
  yPos = 20;

  // 1. Executive Summary
  doc.setFontSize(14);
  doc.setTextColor(245, 139, 68);
  doc.text('1. EXECUTIVE SUMMARY', 20, yPos);
  yPos += 10;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  const summaryData = [
    ['Issue Type', data.formData.issueType],
    ['Property Location', `${data.formData.location}, ${data.formData.city}, ${data.formData.state}`],
    ['Escalation Level', data.formData.escalationLevel],
    ['Urgency Level', data.formData.urgencyLevel],
    ['Affected Residents', data.formData.affectedResidents || 'Not specified'],
    ['Property Age', data.formData.propertyAge || 'Not specified'],
    ['Total Estimated Damages', data.totalCost ? `$${data.totalCost.toLocaleString()}` : 'Not calculated']
  ];

  doc.autoTable({
    startY: yPos,
    head: [['Category', 'Details']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [245, 139, 68] },
    margin: { left: 20, right: 20 }
  });

  yPos = doc.lastAutoTable.finalY + 15;

  // 2. Issue Details
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }

  doc.setFontSize(14);
  doc.setTextColor(245, 139, 68);
  doc.text('2. ISSUE DETAILS', 20, yPos);
  yPos += 10;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  // Evidence
  if (data.formData.evidence) {
    doc.setFont(undefined, 'bold');
    doc.text('Evidence Description:', 20, yPos);
    doc.setFont(undefined, 'normal');
    yPos += 7;

    const evidenceLines = doc.splitTextToSize(data.formData.evidence, 170);
    evidenceLines.forEach(line => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(line, 20, yPos);
      yPos += 6;
    });
    yPos += 5;
  }

  // Measurements
  if (data.formData.measurements) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFont(undefined, 'bold');
    doc.text('Measurements / Test Results:', 20, yPos);
    doc.setFont(undefined, 'normal');
    yPos += 7;

    const measurementLines = doc.splitTextToSize(data.formData.measurements, 170);
    measurementLines.forEach(line => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(line, 20, yPos);
      yPos += 6;
    });
    yPos += 5;
  }

  // Health Impact
  if (data.formData.healthImpact) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFont(undefined, 'bold');
    doc.text('Health Impact:', 20, yPos);
    doc.setFont(undefined, 'normal');
    yPos += 7;

    const healthLines = doc.splitTextToSize(data.formData.healthImpact, 170);
    healthLines.forEach(line => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(line, 20, yPos);
      yPos += 6;
    });
    yPos += 5;
  }

  // 3. Timeline
  if (data.timeline && data.timeline.length > 0) {
    doc.addPage();
    yPos = 20;

    doc.setFontSize(14);
    doc.setTextColor(245, 139, 68);
    doc.text('3. TIMELINE OF EVENTS', 20, yPos);
    yPos += 10;

    const timelineData = data.timeline
      .filter(e => e.date && e.description)
      .sort((a, b) => new Date(a.date) - new Date(b.date))
      .map(event => {
        const date = new Date(event.date).toLocaleDateString();
        const time = event.time || '';
        return [date, time, event.description];
      });

    doc.autoTable({
      startY: yPos,
      head: [['Date', 'Time', 'Event']],
      body: timelineData,
      theme: 'grid',
      headStyles: { fillColor: [245, 139, 68] },
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 25 },
        2: { cellWidth: 'auto' }
      }
    });

    yPos = doc.lastAutoTable.finalY + 15;
  }

  // 4. Damage Assessment
  if (data.totalCost && data.totalCost > 0) {
    if (yPos > 220 || !data.timeline) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(245, 139, 68);
    doc.text('4. DAMAGE ASSESSMENT', 20, yPos);
    yPos += 10;

    doc.setFontSize(16);
    doc.setTextColor(245, 139, 68);
    doc.setFont(undefined, 'bold');
    doc.text(`Total Estimated Damages: $${data.totalCost.toLocaleString()}`, 20, yPos);
    doc.setFont(undefined, 'normal');
    yPos += 10;

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text('(Detailed breakdown included in appendices)', 20, yPos);
  }

  // 7. Advocacy Email
  if (data.generatedEmail) {
    doc.addPage();
    yPos = 20;

    doc.setFontSize(14);
    doc.setTextColor(245, 139, 68);
    doc.text('7. ADVOCACY EMAIL', 20, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);

    doc.setFont(undefined, 'bold');
    doc.text('Subject:', 20, yPos);
    doc.setFont(undefined, 'normal');
    yPos += 7;
    doc.text(data.generatedSubject, 20, yPos);
    yPos += 10;

    const emailLines = doc.splitTextToSize(data.generatedEmail, 170);
    emailLines.forEach(line => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(line, 20, yPos);
      yPos += 6;
    });
  }

  // Footer on all pages
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text('HomeLLM Evidence Packet - Confidential', 105, 285, { align: 'center' });
  }

  // Save
  const filename = `HomeLLM_Evidence_Packet_${data.formData.issueType}_${Date.now()}.pdf`;
  doc.save(filename);
}

/**
 * Export document analysis as PDF
 */
export function exportAnalysisAsPDF(analysisText, documentType, filename) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(245, 139, 68);
  doc.text('HomeLLM', 20, 20);

  doc.setFontSize(14);
  doc.setTextColor(75, 81, 97);
  doc.text(`${documentType} Analysis Report`, 20, 30);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 38);

  // Line
  doc.setDrawColor(245, 139, 68);
  doc.setLineWidth(0.5);
  doc.line(20, 42, 190, 42);

  // Analysis text
  let yPos = 55;
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  const lines = doc.splitTextToSize(analysisText, 170);
  lines.forEach(line => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, 20, yPos);
    yPos += 6;
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }

  doc.save(filename || `Analysis_${Date.now()}.pdf`);
}

export default {
  exportEmailAsPDF,
  exportEvidencePacket,
  exportAnalysisAsPDF
};
